### ISSUE TITLE
Turn tracking

### ISSUE THREAD

**Issue by Mirv** [Benaou/chess#5]
Several spots need to work ... flow should be ... 

**Server.js**

- [ ] initialize (createnew)
- [ ] change in how 201-209 works in server.js
- createNewBoard/joinBoard work (82-121)
  - that's where the 'boardStateId' API response is generated
  - probably nothing too radical needs to be changed, just need to make sure the connection is added initially in createNewBoard
  - [ ] maybe increment the connArrId to 1 automatically?
  - 'connArrId': 1 is what I was thinking since createNewBoard only happens if that gameStateObj[boardStateId] doesn't already exist
  - refactor later:  although there may be some justification in just merging those two functions (createNewBoard / joinBoard) into one and handling each case in the same function

**multiplayer_chess.html**
- [ ] test it in json logged to console
- [ ] wrap the canvas in a div to keep it separate & position the other stuff we build
- [ ] make div to shove it into
